export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_IPS = "UPDATE_IPS";
export const UPDATE_LANDING_PAGE = "UPDATE_LANDING_PAGE";
export const UPDATE_LANDING_PAGE_LIST = "UPDATE_LANDING_PAGE_LIST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const UPDATE_GENERAL_STATE_VALUES = "UPDATE_GENERAL_STATE_VALUES";
export const UPDATE_LP_STATE_VALUES = "UPDATE_LP_STATE_VALUES";
export const UPDATE_LIST_DELETE_VALUES = "UPDATE_LIST_DELETE_VALUES";
export const LOGOUT = "LOGOUT";

export const APP_USERS = "APP_USERS";

export const SET_TOAST = "SET_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
